steps:
  - uses: actions/checkout@v2
  - name: Run OSSAR
    uses: github/ossar-action@v1
    id: ossar
  - name: Upload results to Security tab
    uses: github/codeql-action/upload-sarif@v1
    with:
      sarif_file: ${{ steps.ossar.outputs.sarifFile }}
